import {ObjectId} from "mongodb";

export interface Legislation {
  id: string;
  identifier?: string;
  title?: string;
  session?: string;
  jurisdictionId?: string;
  jurisdictionName?: string;
  chamber?: string | null;
  classification?: string[];
  subjects?: string[];
  statusText?: string | null;
  sponsors?: any[];
  history?: any[];
  versions?: any[];
  sources?: any[];
  abstracts?: any[];
  openstatesUrl?: string;
  congressUrl?: string;
  firstActionAt?: Date | null;
  latestActionAt?: Date | null;
  latestActionDescription?: string | null;
  latestPassageAt?: Date | null;
  createdAt?: Date;
  updatedAt?: Date;
  stateLegislatureUrl: string;
  fullText?: string | null; // Full text of the legislation, if available
  geminiSummary?: string | null; // Summary generated by Gemini
  longGeminiSummary?: string | null; // Detailed summary generated by Gemini from full text/PDF sources
  geminiSummarySource?: string | null; // Source type used for generating the summary (pdf-extracted, abstracts, title, etc.)
  summary?: string | null;
  extras?: Record<string, any> | null;
  topicClassification?: {
    broadTopics: string[],
    narrowTopics: string[],
    confidence: number,
    reasoning: string,
    classifiedAt: Date | null;
  }
  // Performance optimization field
  enactedAt?: Date | null; // Date when the legislation was enacted (null if not enacted)
  enactedFieldUpdatedAt?: Date; // When the enactedAt field was last computed
}

// Bookmark/SavedLegislation Types
export interface BookmarkMetadata {
  tags?: string[];
  notes?: string;
  priority?: 'low' | 'medium' | 'high';
  customTitle?: string;
}

export interface LegislationBookmark {
  id: string; // Unique bookmark ID
  userId: string; // Clerk user ID
  legislationId: string; // ID of the saved legislation
  createdAt: Date;
  updatedAt: Date;
  metadata?: BookmarkMetadata;
}

// MongoDB document type for bookmarks
export interface BookmarkMongoDbDocument extends Omit<LegislationBookmark, 'id' | 'createdAt' | 'updatedAt'> {
  _id: import('mongodb').ObjectId;
  id: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface BookmarkButtonProps {
  legislationId: string;
  className?: string;
}

export interface LegislationMongoDbDocument extends Omit<Legislation, 'id' | 'createdAt' | 'updatedAt'> {
  _id: ObjectId;
  id: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface RelatedLegislation {
  id: string;
  title?: string;
  identifier?: string;
  jurisdictionName?: string;
  latestActionAt?: string;
  latestActionDescription?: string;
  subjects?: string[];
  stateLegislatureUrl?: string;
  statusText?: string;
  classification?: string[];
  session?: string;
  chamber?: string;
  firstActionAt?: string;
  sponsors?: { name: string }[];
  abstracts?: { abstract: string }[];
  geminiSummary?: string;
  openstatesUrl?: string;
  congressUrl?: string;
  topicClassification?: {
    broadTopics: string[];
    narrowTopics: string[];
    confidence: number;
    reasoning: string;
    classifiedAt: Date | null;
  };
}

export interface Bill {
  id: string;
  identifier: string;
  title: string;
  subject: string[];
  classification: string[];
  from_organization?: {
    name: string;
  };
  latest_action_description?: string;
  latest_action_date?: string;
  abstract?: string;
}

export interface BillSearchProps {
  selectedBills: Bill[];
  onBillSelect: (bill: Bill) => void;
  userLocation?: {
    state?: string;
    city?: string;
  };
  className?: string;
}

export const enactedPatterns = [
  /signed.*(into|by).*(law|governor)/i,
  /approved.*by.*governor/i,
  /became.*law/i,
  /effective.*date/i,
  /chapter.*laws/i,
  /public.*law.*no/i,
  /acts.*of.*assembly.*chapter/i,
  /governor.*signed/i,
  /signed.*into.*law/i,
  /notification.*is.*now.*act/i,
  /approved.*p.*l.*c/i,
  /signed.*chap/i,
  /signed.*by.*gov/i
];

export const BROAD_TOPIC_KEYWORDS: Record<string, string[]> = {
  'Agriculture and Food': [
    'agriculture', 'agricultural', 'farm', 'farming', 'farmer', 'crop', 'crops', 'livestock', 'cattle', 'beef', 'pork', 'poultry', 'chicken', 'dairy', 'milk', 'food', 'nutrition', 'organic', 'pesticide', 'fertilizer', 'irrigation', 'harvest', 'grain', 'wheat', 'corn', 'soybean', 'vegetable', 'fruit', 'meat', 'fish', 'seafood', 'aquaculture', 'horticulture', 'forestry', 'ranch', 'pasture', 'rural development'
  ],
  'Animals': [
    'animal', 'animals', 'pet', 'pets', 'wildlife', 'endangered species', 'conservation', 'habitat', 'zoo', 'veterinary', 'vet', 'dog', 'cat', 'horse', 'bird', 'fish', 'mammal', 'reptile', 'amphibian', 'animal welfare', 'animal rights', 'cruelty', 'abuse', 'protection', 'sanctuary'
  ],
  'Armed Forces and National Security': [
    'military', 'defense', 'army', 'navy', 'air force', 'marines', 'coast guard', 'veteran', 'veterans', 'national security', 'homeland security', 'intelligence', 'warfare', 'combat', 'soldier', 'weapon', 'weapons', 'missile', 'nuclear', 'terrorism', 'counterterrorism', 'classified', 'surveillance', 'espionage'
  ],
  'Arts, Culture, Religion': [
    'art', 'arts', 'culture', 'cultural', 'museum', 'library', 'music', 'theater', 'theatre', 'dance', 'film', 'movie', 'television', 'radio', 'broadcasting', 'literature', 'book', 'religion', 'religious', 'church', 'faith', 'spiritual', 'worship', 'prayer', 'ceremony', 'festival', 'heritage', 'historic', 'monument'
  ],
  'Civil Rights and Liberties, Minority Issues': [
    'civil rights', 'discrimination', 'equality', 'equal protection', 'due process', 'first amendment', 'freedom of speech', 'freedom of religion', 'privacy', 'minority', 'racial', 'ethnic', 'gender', 'sexual orientation', 'disability', 'accessibility', 'voting rights', 'abortion', 'reproductive rights', 'lgbt', 'lgbtq', 'transgender', 'gay', 'lesbian'
  ],
  'Commerce': [
    'business', 'commerce', 'trade', 'industry', 'manufacturing', 'retail', 'wholesale', 'market', 'competition', 'antitrust', 'consumer', 'intellectual property', 'patent', 'trademark', 'copyright', 'small business', 'entrepreneur', 'startup', 'corporation', 'company', 'economic development', 'investment'
  ],
  'Chamber': [
    'congress', 'congressional', 'house of representatives', 'senate', 'senator', 'representative', 'committee', 'subcommittee', 'hearing', 'testimony', 'oversight', 'investigation', 'ethics', 'lobbying', 'campaign finance', 'election', 'voting', 'ballot', 'political'
  ],
  'Crime and Law Enforcement': [
    'crime', 'criminal', 'police', 'law enforcement', 'officer', 'arrest', 'investigation', 'prosecution', 'court', 'trial', 'sentence', 'prison', 'jail', 'incarceration', 'parole', 'probation', 'drug', 'narcotics', 'trafficking', 'fraud', 'theft', 'robbery', 'assault', 'murder', 'homicide', 'violence', 'gang', 'juvenile'
  ],
  'Economics and Public Finance': [
    'budget', 'appropriation', 'spending', 'revenue', 'tax', 'taxation', 'fiscal', 'monetary', 'economy', 'economic', 'finance', 'financial', 'debt', 'deficit', 'surplus', 'inflation', 'recession', 'growth', 'gdp', 'employment', 'unemployment', 'interest rate', 'federal reserve'
  ],
  'Education': [
    'education', 'educational', 'school', 'schools', 'student', 'students', 'teacher', 'teachers', 'university', 'college', 'higher education', 'elementary', 'secondary', 'k-12', 'curriculum', 'learning', 'academic', 'degree', 'diploma', 'scholarship', 'student loan', 'tuition', 'special education', 'vocational'
  ],
  'Emergency Management': [
    'emergency', 'disaster', 'hurricane', 'tornado', 'earthquake', 'flood', 'fire', 'wildfire', 'drought', 'storm', 'evacuation', 'relief', 'response', 'recovery', 'preparedness', 'first responder', 'fema', 'homeland security', 'crisis', 'pandemic'
  ],
  'Energy': [
    'energy', 'power', 'electricity', 'electric', 'oil', 'gas', 'natural gas', 'coal', 'nuclear', 'renewable', 'solar', 'wind', 'hydroelectric', 'geothermal', 'biomass', 'utility', 'utilities', 'grid', 'pipeline', 'drilling', 'fracking', 'conservation', 'efficiency', 'fuel'
  ],
  'Environmental Protection': [
    'environment', 'environmental', 'pollution', 'air quality', 'water quality', 'climate', 'climate change', 'greenhouse gas', 'carbon', 'emission', 'toxic', 'hazardous', 'waste', 'recycling', 'conservation', 'ecosystem', 'biodiversity', 'endangered', 'clean air', 'clean water', 'superfund', 'epa'
  ],
  'Families': [
    'family', 'families', 'child', 'children', 'parent', 'parents', 'marriage', 'divorce', 'custody', 'adoption', 'foster care', 'domestic violence', 'child abuse', 'child welfare', 'childcare', 'parental leave', 'family leave'
  ],
  'Finance and Financial Sector': [
    'bank', 'banking', 'financial institution', 'credit', 'loan', 'mortgage', 'insurance', 'securities', 'investment', 'stock', 'bond', 'mutual fund', 'pension', 'retirement', '401k', 'ira', 'bankruptcy', 'foreclosure', 'consumer protection', 'fdic'
  ],
  'Foreign Trade and International Finance': [
    'trade', 'international trade', 'export', 'exports', 'import', 'imports', 'tariff', 'tariffs', 'trade agreement', 'nafta', 'wto', 'customs', 'foreign investment', 'international', 'globalization', 'competitiveness'
  ],
  'Government Operations and Politics': [
    'government', 'federal', 'agency', 'department', 'administration', 'bureaucracy', 'regulation', 'rulemaking', 'procurement', 'contract', 'contracting', 'personnel', 'employee', 'civil service', 'ethics', 'transparency', 'accountability', 'audit', 'inspector general'
  ],
  'Health': [
    'health', 'healthcare', 'medical', 'medicine', 'hospital', 'clinic', 'doctor', 'physician', 'nurse', 'patient', 'disease', 'illness', 'treatment', 'therapy', 'drug', 'pharmaceutical', 'prescription', 'medicare', 'medicaid', 'insurance', 'mental health', 'public health', 'epidemic', 'vaccine'
  ],
  'Housing and Community Development': [
    'housing', 'home', 'homeownership', 'mortgage', 'rent', 'rental', 'affordable housing', 'public housing', 'homeless', 'homelessness', 'community development', 'urban development', 'rural development', 'neighborhood', 'construction', 'building', 'real estate', 'property'
  ],
  'Immigration': [
    'immigration', 'immigrant', 'immigrants', 'visa', 'citizenship', 'naturalization', 'border', 'deportation', 'asylum', 'refugee', 'undocumented', 'illegal immigration', 'green card', 'h1b', 'daca', 'dreamers', 'customs', 'ice', 'border patrol'
  ],
  'International Affairs': [
    'foreign policy', 'international', 'diplomacy', 'ambassador', 'embassy', 'treaty', 'alliance', 'united nations', 'nato', 'foreign aid', 'humanitarian', 'peace', 'conflict', 'war', 'sanctions', 'human rights', 'democracy'
  ],
  'Labor and Employment': [
    'labor', 'employment', 'worker', 'workers', 'job', 'jobs', 'workplace', 'union', 'collective bargaining', 'wage', 'wages', 'salary', 'minimum wage', 'overtime', 'benefits', 'unemployment', 'workforce', 'training', 'apprenticeship', 'occupational safety', 'osha'
  ],
  'Law': [
    'law', 'legal', 'court', 'courts', 'judge', 'judges', 'justice', 'judicial', 'litigation', 'lawsuit', 'attorney', 'lawyer', 'legal services', 'civil procedure', 'criminal procedure', 'constitutional', 'statute', 'regulation', 'compliance'
  ],
  'Native Americans': [
    'native american', 'indian', 'tribe', 'tribal', 'reservation', 'alaska native', 'hawaiian native', 'indigenous', 'sovereignty', 'treaty', 'casino', 'gaming', 'land rights', 'cultural preservation'
  ],
  'Public Lands and Natural Resources': [
    'public land', 'national park', 'national forest', 'wilderness', 'monument', 'recreation', 'hunting', 'fishing', 'mining', 'timber', 'logging', 'grazing', 'land management', 'blm', 'forest service', 'national wildlife refuge'
  ],
  'Science, Technology, Communications': [
    'science', 'scientific', 'research', 'technology', 'innovation', 'internet', 'cyber', 'cybersecurity', 'computer', 'software', 'telecommunications', 'broadband', 'wireless', 'satellite', 'space', 'nasa', 'nsf', 'nih', 'stem', 'artificial intelligence', 'ai'
  ],
  'Social Sciences and History': [
    'history', 'historical', 'social science', 'sociology', 'psychology', 'anthropology', 'archaeology', 'economics', 'political science', 'geography', 'statistics', 'census', 'demographic'
  ],
  'Social Welfare': [
    'welfare', 'social security', 'disability', 'food stamps', 'snap', 'tanf', 'medicaid', 'social services', 'poverty', 'assistance', 'benefits', 'elderly', 'senior', 'aging', 'community service', 'volunteer', 'charity', 'nonprofit'
  ],
  'Sports and Recreation': [
    'sports', 'recreation', 'athletics', 'athlete', 'olympic', 'ncaa', 'professional sports', 'amateur sports', 'physical fitness', 'exercise', 'gym', 'park', 'recreation center', 'youth sports', 'coaching'
  ],
  'Taxation': [
    'tax', 'taxes', 'taxation', 'income tax', 'corporate tax', 'property tax', 'sales tax', 'excise tax', 'tax credit', 'tax deduction', 'tax reform', 'irs', 'tax code', 'tax collection', 'tax evasion', 'tax compliance'
  ],
  'Transportation and Public Works': [
    'transportation', 'highway', 'road', 'bridge', 'infrastructure', 'public works', 'transit', 'bus', 'rail', 'railroad', 'airport', 'aviation', 'port', 'shipping', 'vehicle', 'automobile', 'truck', 'motorcycle', 'bicycle', 'pedestrian', 'traffic', 'dot'
  ],
  'Water Resources Development': [
    'water', 'water resources', 'dam', 'reservoir', 'flood', 'drought', 'irrigation', 'watershed', 'river', 'lake', 'groundwater', 'aquifer', 'water supply', 'water treatment', 'wastewater', 'sewage', 'wetland', 'corps of engineers'
  ]
};

// Narrow topic categories with associated keywords
export const NARROW_TOPIC_KEYWORDS: Record<string, string[]> = {
  'Abortion': ['abortion', 'reproductive rights', 'pro-choice', 'pro-life', 'planned parenthood', 'contraception', 'birth control'],
  'Academic performance and assessments': ['test scores', 'standardized testing', 'assessment', 'evaluation', 'academic achievement', 'performance standards'],
  'Accidents': ['accident', 'accidents', 'crash', 'collision', 'workplace accident', 'safety incident'],
  'Accounting and auditing': ['accounting', 'audit', 'auditing', 'financial records', 'bookkeeping', 'cpa', 'gaap'],
  'Administrative law and regulatory procedures': ['rulemaking', 'administrative procedure', 'regulatory process', 'federal register', 'notice and comment', 'agency action'],
  'Administrative remedies': ['administrative remedy', 'administrative appeal', 'agency review', 'administrative hearing'],
  'Adoption and foster care': ['adoption', 'foster care', 'child placement', 'foster family', 'adoptive parent'],
  'Adult day care': ['adult day care', 'senior day care', 'adult care center', 'daytime care'],
  'Adult education and literacy': ['adult education', 'literacy', 'ged', 'continuing education', 'adult learning'],
  'Advanced technology and technological innovations': ['advanced technology', 'innovation', 'emerging technology', 'tech innovation', 'technological advancement'],
  'Advisory bodies': ['advisory committee', 'advisory board', 'commission', 'task force', 'panel'],
  'Age discrimination': ['age discrimination', 'ageism', 'elderly discrimination', 'age bias'],
  'Aging': ['elderly', 'senior citizens', 'aging', 'geriatric', 'nursing home', 'assisted living', 'social security', 'medicare'],
  'Agricultural conservation and pollution': ['agricultural conservation', 'farm pollution', 'soil conservation', 'agricultural runoff'],
  'Agricultural education': ['agricultural education', 'farm education', 'agriculture training', 'agricultural extension'],
  'Agricultural equipment and machinery': ['farm equipment', 'agricultural machinery', 'tractors', 'farm tools'],
  'Agricultural insurance': ['crop insurance', 'farm insurance', 'agricultural insurance', 'livestock insurance'],
  'Agricultural marketing and promotion': ['agricultural marketing', 'farm marketing', 'crop promotion', 'agricultural advertising'],
  'Agricultural practices and innovations': ['sustainable agriculture', 'precision farming', 'agricultural technology', 'biotechnology', 'gmo', 'crop rotation'],
  'Agricultural prices, subsidies, credit': ['farm subsidies', 'agricultural prices', 'farm credit', 'crop prices'],
  'Agricultural research': ['agricultural research', 'farm research', 'crop research', 'livestock research'],
  'Agricultural trade': ['agricultural trade', 'farm exports', 'agricultural imports', 'crop trade'],
  'Air quality': ['air pollution', 'emissions', 'smog', 'particulate matter', 'ozone', 'clean air act', 'air standards'],
  'Alaska Natives and Hawaiians': ['alaska native', 'hawaiian native', 'native hawaiian', 'indigenous alaska'],
  'Alcoholic beverages': ['alcohol', 'beer', 'wine', 'spirits', 'liquor', 'alcoholic beverages'],
  'Allergies': ['allergies', 'allergic reaction', 'food allergies', 'allergens'],
  'Alliances': ['alliance', 'coalition', 'partnership', 'treaty alliance', 'international alliance'],
  'Alternative and renewable resources': ['renewable energy', 'solar power', 'wind power', 'alternative energy', 'clean energy'],
  'Alternative dispute resolution, mediation, arbitration': ['mediation', 'arbitration', 'dispute resolution', 'adr', 'conflict resolution'],
  'Alternative treatments': ['alternative medicine', 'complementary medicine', 'holistic treatment', 'natural remedies'],
  'Animal and plant health': ['animal health', 'plant health', 'veterinary health', 'crop disease'],
  'Animal protection and human-animal relationships': ['animal welfare', 'animal rights', 'pet protection', 'animal cruelty', 'wildlife protection'],
  'Appropriations': ['appropriation', 'funding bill', 'budget allocation', 'spending bill'],
  'Aquaculture': ['aquaculture', 'fish farming', 'shellfish farming', 'marine farming'],
  'Aquatic ecology': ['aquatic ecology', 'marine ecosystem', 'water ecosystem', 'aquatic environment'],
  'Arab-Israeli relations': ['arab israeli', 'middle east peace', 'israel palestine', 'israeli conflict'],
  'Archaeology and anthropology': ['archaeology', 'anthropology', 'cultural heritage', 'archaeological site'],
  'Architecture': ['architecture', 'building design', 'architectural standards', 'structural design'],
  'Arctic and polar regions': ['arctic', 'polar', 'antarctica', 'ice cap', 'polar research'],
  'Area studies and international education': ['international studies', 'area studies', 'foreign studies', 'cultural studies'],
  'Arms control and nonproliferation': ['arms control', 'nonproliferation', 'nuclear disarmament', 'weapons control'],
  'Art, artists, authorship': ['art', 'artist', 'authorship', 'creative work', 'artistic expression'],
  'Assault and harassment offenses': ['assault', 'harassment', 'battery', 'threatening behavior', 'intimidation'],
  'Athletes': ['athlete', 'sports player', 'professional athlete', 'olympic athlete'],
  'Atmospheric science and weather': ['weather', 'meteorology', 'atmospheric science', 'climate science', 'weather forecasting'],
  'Aviation and airports': ['aviation', 'airport', 'aircraft', 'airline', 'flight safety', 'air traffic'],
  'Bank accounts, deposits, capital': ['bank account', 'deposits', 'bank capital', 'savings account', 'checking account'],
  'Banking and financial institutions regulation': ['bank regulation', 'financial oversight', 'dodd-frank', 'basel', 'capital requirements', 'stress test'],
  'Bankruptcy': ['bankruptcy', 'insolvency', 'debt relief', 'chapter 7', 'chapter 11'],
  'Biological and life sciences': ['biology', 'life sciences', 'biotechnology', 'biomedical research'],
  'Birds': ['birds', 'avian', 'migratory birds', 'bird protection', 'ornithology'],
  'Birth defects': ['birth defects', 'congenital disorders', 'genetic disorders', 'developmental disorders'],
  'Blood and blood diseases': ['blood disease', 'blood disorder', 'anemia', 'blood transfusion', 'hematology'],
  'Books and print media': ['books', 'publishing', 'print media', 'literature', 'printed materials'],
  'Border security and unlawful immigration': ['border security', 'illegal immigration', 'border patrol', 'undocumented immigrants', 'border wall'],
  'Broadcasting, cable, digital technologies': ['broadcasting', 'cable tv', 'digital technology', 'television broadcasting', 'radio broadcasting'],
  'Budget deficits and national debt': ['deficit', 'national debt', 'debt ceiling', 'fiscal responsibility', 'government spending', 'debt reduction'],
  'Budget process': ['budget process', 'budget planning', 'fiscal planning', 'budget procedure'],
  'Building construction': ['construction', 'building', 'construction industry', 'building codes', 'construction safety'],
  'Business education': ['business education', 'business training', 'entrepreneurship education', 'business school'],
  'Business ethics': ['business ethics', 'corporate ethics', 'business integrity', 'ethical business practices'],
  'Business expenses': ['business expenses', 'business costs', 'business deductions', 'operating expenses'],
  'Business investment and capital': ['business investment', 'capital investment', 'business funding', 'venture capital'],
  'Business records': ['business records', 'corporate records', 'business documentation', 'record keeping'],
  'Buy American requirements': ['buy american', 'domestic preference', 'american made', 'domestic sourcing'],
  'Cancer': ['cancer research', 'oncology', 'tumor', 'chemotherapy', 'radiation therapy', 'cancer treatment', 'malignancy'],
  'Capital gains tax': ['capital gains', 'investment tax', 'capital gains tax', 'investment income'],
  'Cardiovascular and respiratory health': ['heart disease', 'cardiovascular', 'respiratory health', 'lung disease', 'heart health'],
  'Cell biology and embryology': ['cell biology', 'embryology', 'stem cell', 'cellular research'],
  'Cemeteries and funerals': ['cemetery', 'funeral', 'burial', 'memorial service', 'funeral home'],
  'Census and government statistics': ['census', 'statistics', 'demographic data', 'population count', 'survey'],
  'Charitable contributions': ['charity', 'charitable giving', 'donation', 'philanthropic', 'tax deductible'],
  'Chemical and biological weapons': ['chemical weapons', 'biological weapons', 'wmd', 'chemical warfare'],
  'Chemistry': ['chemistry', 'chemical research', 'chemical science', 'chemical analysis'],
  'Child care and development': ['childcare', 'child development', 'early childhood', 'daycare', 'preschool'],
  'Child health': ['pediatric', 'children\'s health', 'immunization', 'child nutrition', 'child safety', 'infant mortality'],
  'Child safety and welfare': ['child safety', 'child welfare', 'child protection', 'child services', 'child abuse prevention'],
  'Citizenship and naturalization': ['citizenship', 'naturalization', 'naturalized citizen', 'citizenship test'],
  'Civics education': ['civics', 'civic education', 'government education', 'citizenship education'],
  'Civil actions and liability': ['lawsuit', 'tort', 'damages', 'liability', 'civil litigation', 'personal injury', 'negligence'],
  'Civil disturbances': ['civil unrest', 'riots', 'civil disturbance', 'public disorder'],
  'Climate change and greenhouse gases': ['global warming', 'carbon emissions', 'greenhouse effect', 'climate science', 'carbon tax', 'cap and trade'],
  'Coal': ['coal', 'coal mining', 'coal power', 'coal industry', 'clean coal'],
  'Coast guard': ['coast guard', 'maritime security', 'coastal protection', 'marine safety'],
  'Collective security': ['collective security', 'mutual defense', 'security alliance', 'defense pact'],
  'Commemorative events and holidays': ['commemoration', 'holiday', 'memorial day', 'national day', 'celebration'],
  'Commodities markets': ['commodities', 'commodity trading', 'futures market', 'commodity exchange'],
  'Community life and organization': ['community organization', 'neighborhood', 'community development', 'local community'],
  'Commuting': ['commuting', 'commuter', 'public transportation', 'transit', 'work travel'],
  'Competition and antitrust': ['antitrust', 'competition', 'monopoly', 'market competition', 'fair trade'],
  'Competitiveness, trade promotion, trade deficits': ['trade competitiveness', 'trade promotion', 'trade deficit', 'export promotion'],
  'Comprehensive health care': ['universal healthcare', 'comprehensive health', 'health coverage', 'healthcare reform'],
  'Computer security and identity theft': ['cybersecurity', 'identity theft', 'data security', 'computer security', 'cyber crime'],
  'Computers and information technology': ['computer', 'information technology', 'software', 'hardware', 'digital'],
  'Conflicts and wars': ['war', 'conflict', 'military conflict', 'armed conflict', 'warfare'],
  'Agencies': ['congressional agency', 'legislative agency', 'congress support', 'parliamentary service'],
  'Committees': ['committee', 'subcommittee', 'congressional committee', 'house committee', 'senate committee'],
  'Districts and representation': ['congressional district', 'representation', 'redistricting', 'gerrymandering'],
  'Elections': ['congressional election', 'house election', 'senate election', 'midterm election'],
  'Leadership': ['speaker', 'majority leader', 'minority leader', 'congressional leadership'],
  'Officers and employees': ['congressional staff', 'house staff', 'senate staff', 'legislative staff'],
  'Operations and organization': ['congress operations', 'legislative process', 'congressional procedure'],
  'Oversight': ['oversight hearing', 'investigation', 'subpoena', 'government accountability', 'inspector general'],
  'Tributes': ['tribute', 'congressional recognition', 'honor', 'commemoration'],
  'Executive branch relations': ['separation of powers', 'executive privilege', 'congress executive', 'legislative executive'],
  'Constitution and constitutional amendments': ['constitution', 'constitutional amendment', 'constitutional law', 'bill of rights'],
  'Consumer affairs': ['consumer protection', 'product safety', 'fraud prevention', 'consumer rights', 'false advertising'],
  'Consumer credit': ['consumer credit', 'credit card', 'personal loan', 'consumer debt'],
  'Contracts and agency': ['contract', 'contractual agreement', 'agency relationship', 'legal contract'],
  'Cooperative and condominium housing': ['cooperative housing', 'condo', 'condominium', 'housing cooperative'],
  'Corporate finance and management': ['corporate finance', 'corporate management', 'business finance', 'corporate governance'],
  'Correctional facilities and imprisonment': ['prison', 'correctional facility', 'incarceration', 'jail', 'penitentiary'],
  'Cosmetics and personal care': ['cosmetics', 'personal care', 'beauty products', 'skincare'],
  'Credit and credit markets': ['credit market', 'lending', 'credit system', 'credit rating'],
  'Crime prevention': ['community policing', 'crime reduction', 'public safety', 'neighborhood watch', 'violence prevention'],
  'Crime victims': ['victim', 'crime victim', 'victim services', 'victim compensation', 'victim rights'],
  'Crimes against animals and natural resources': ['poaching', 'wildlife crime', 'environmental crime', 'animal cruelty'],
  'Crimes against children': ['child abuse', 'child exploitation', 'child pornography', 'crimes against minors'],
  'Crimes against property': ['property crime', 'theft', 'burglary', 'vandalism', 'arson'],
  'Crimes against women': ['domestic violence', 'violence against women', 'sexual assault', 'gender violence'],
  'Criminal investigation, prosecution, interrogation': ['investigation', 'prosecutor', 'district attorney', 'interrogation', 'evidence', 'forensics'],
  'Criminal justice information and records': ['criminal records', 'background check', 'criminal database', 'justice information'],
  'Criminal procedure and sentencing': ['criminal procedure', 'sentencing', 'criminal trial', 'plea bargain'],
  'Cultural exchanges and relations': ['cultural exchange', 'cultural diplomacy', 'international culture', 'cultural program'],
  'Currency': ['currency', 'money', 'dollar', 'monetary system', 'exchange rate'],
  'Customs enforcement': ['customs', 'border customs', 'import control', 'customs inspection'],
  'Dams and canals': ['dam', 'canal', 'waterway', 'water infrastructure', 'reservoir'],
  'Debt collection': ['debt collection', 'debt recovery', 'collection agency', 'debt collector'],
  'Defense spending': ['defense budget', 'military spending', 'defense expenditure', 'military budget'],
  'Dental care': ['dental', 'dentist', 'oral health', 'dental treatment', 'teeth'],
  'Detention of persons': ['detention', 'custody', 'holding facility', 'detainee'],
  'Digestive and metabolic diseases': ['digestive disease', 'metabolic disorder', 'diabetes', 'gastrointestinal'],
  'Digital media': ['digital media', 'online content', 'digital publishing', 'multimedia'],
  'Diplomacy, foreign officials, Americans abroad': ['diplomacy', 'diplomat', 'embassy', 'foreign service', 'americans abroad'],
  'Disability and health-based discrimination': ['disability discrimination', 'health discrimination', 'ada', 'disability rights'],
  'Disability and paralysis': ['disability', 'paralysis', 'disabled', 'mobility impairment', 'assistive technology'],
  'Disability assistance': ['disability benefits', 'disability services', 'disability support', 'accommodation'],
  'Disaster relief and insurance': ['disaster relief', 'emergency aid', 'disaster insurance', 'fema assistance'],
  'Domestic violence and child abuse': ['domestic violence', 'child abuse', 'family violence', 'intimate partner violence'],
  'Drug safety, medical device, and laboratory regulation': ['fda', 'drug approval', 'clinical trials', 'medical device', 'pharmaceutical safety'],
  'Drug therapy': ['drug therapy', 'medication', 'pharmaceutical treatment', 'drug treatment'],
  'Drug trafficking and controlled substances': ['drug trafficking', 'narcotics', 'controlled substances', 'drug dealing', 'illegal drugs'],
  'Drug, alcohol, tobacco use': ['substance abuse', 'drug use', 'alcohol abuse', 'tobacco use', 'addiction'],
  'Due process and equal protection': ['due process', 'equal protection', 'constitutional rights', 'civil liberties'],
  'Earth sciences': ['geology', 'earth science', 'geophysics', 'environmental science'],
  'Ecology': ['ecology', 'ecosystem', 'environmental biology', 'ecological research'],
  'Economic development': ['job creation', 'business development', 'economic growth', 'industrial development', 'entrepreneurship'],
  'Economic performance and conditions': ['economic conditions', 'economic performance', 'economic indicators', 'economic analysis'],
  'Education of the disadvantaged': ['disadvantaged students', 'educational equity', 'at-risk students', 'educational opportunity'],
  'Education programs funding': ['school funding', 'education budget', 'title i', 'pell grant', 'education appropriations'],
  'Educational facilities and institutions': ['school building', 'educational facility', 'campus', 'school infrastructure'],
  'Educational guidance': ['counseling', 'academic guidance', 'student counseling', 'career guidance'],
  'Educational technology and distance education': ['educational technology', 'distance learning', 'online education', 'e-learning'],
  'Elections, voting, political campaign regulation': ['election', 'voting', 'campaign finance', 'political campaign', 'electoral process'],
  'Electric power generation and transmission': ['electric power', 'power generation', 'power transmission', 'electricity grid'],
  'Elementary and secondary education': ['k-12', 'elementary school', 'secondary school', 'primary education'],
  'Emergency communications systems': ['emergency communication', 'emergency alert', '911 system', 'emergency broadcast'],
  'Emergency medical services and trauma care': ['ems', 'paramedic', 'ambulance', 'emergency medicine', 'trauma care'],
  'Emergency planning and evacuation': ['emergency response', 'disaster preparedness', 'evacuation plan', 'emergency management', 'crisis response'],
  'Employee benefits and pensions': ['employee benefits', 'pension', 'retirement benefits', 'health benefits'],
  'Employee hiring': ['hiring', 'recruitment', 'employment practices', 'job placement'],
  'Employee leave': ['family leave', 'sick leave', 'maternity leave', 'vacation time'],
  'Employee performance': ['performance evaluation', 'job performance', 'employee assessment', 'productivity'],
  'Employment and training programs': ['job training', 'workforce development', 'employment program', 'skills training'],
  'Employment discrimination and employee rights': ['employment discrimination', 'workplace discrimination', 'employee rights', 'labor rights'],
  'Employment taxes': ['payroll tax', 'employment tax', 'social security tax', 'medicare tax'],
  'Endangered and threatened species': ['endangered species', 'threatened species', 'species protection', 'wildlife conservation'],
  'Energy assistance for the poor and aged': ['energy assistance', 'utility assistance', 'heating assistance', 'low income energy'],
  'Energy efficiency and conservation': ['energy savings', 'conservation programs', 'efficiency standards', 'green building', 'energy star'],
  'Energy prices': ['energy costs', 'fuel prices', 'energy pricing', 'utility rates'],
  'Energy research': ['energy research', 'renewable energy research', 'energy technology', 'energy innovation'],
  'Energy revenues and royalties': ['energy royalties', 'oil royalties', 'mineral rights', 'energy revenue'],
  'Energy storage, supplies, demand': ['energy storage', 'energy supply', 'energy demand', 'power storage'],
  'Environmental assessment, monitoring, research': ['environmental impact', 'environmental study', 'pollution monitoring', 'environmental research'],
  'Environmental education': ['environmental education', 'environmental awareness', 'conservation education'],
  'Environmental health': ['environmental health', 'public health', 'environmental safety', 'health hazards'],
  'Environmental regulatory procedures': ['environmental regulation', 'environmental law', 'environmental compliance'],
  'Environmental technology': ['environmental technology', 'clean technology', 'pollution control', 'green technology'],
  'Espionage and treason': ['espionage', 'spying', 'treason', 'national security', 'intelligence'],
  'Ethnic studies': ['ethnic studies', 'cultural studies', 'minority studies', 'multicultural education'],
  'Evidence and witnesses': ['evidence', 'witness', 'testimony', 'legal evidence', 'court evidence'],
  'Executive agency funding and structure': ['agency funding', 'executive agency', 'federal agency', 'agency structure'],
  'Family planning and birth control': ['family planning', 'birth control', 'contraception', 'reproductive health'],
  'Family relationships': ['marriage', 'divorce', 'child custody', 'domestic relations', 'family court', 'parental rights'],
  'Family services': ['family services', 'family support', 'family assistance', 'social services'],
  'Farmland': ['farmland', 'agricultural land', 'farm property', 'rural land'],
  'Federal appellate courts': ['appellate court', 'court of appeals', 'federal appeals', 'appellate jurisdiction'],
  'Federal district courts': ['district court', 'federal court', 'trial court', 'federal jurisdiction'],
  'Federal officials': ['cabinet', 'federal appointees', 'executive branch', 'federal judges', 'agency heads'],
  'Federal preemption': ['federal preemption', 'supremacy clause', 'federal override', 'state preemption'],
  'Federal-Indian relations': ['indian relations', 'tribal relations', 'native american relations', 'tribal government'],
  'Federally chartered organizations': ['federal charter', 'federally chartered', 'government corporation'],
  'Financial crises and stabilization': ['financial crisis', 'economic crisis', 'financial stability', 'bailout'],
  'Financial literacy': ['financial literacy', 'financial education', 'money management', 'financial skills'],
  'Financial services and investments': ['securities', 'investment advisor', 'broker-dealer', 'mutual funds', 'retirement planning'],
  'Firearms and explosives': ['gun control', 'second amendment', 'firearms regulation', 'background check', 'assault weapons'],
  'Fires': ['fire', 'wildfire', 'fire safety', 'fire prevention', 'arson'],
  'First Amendment rights': ['first amendment', 'free speech', 'freedom of religion', 'freedom of press'],
  'First responders and emergency personnel': ['first responder', 'emergency personnel', 'firefighter', 'police officer', 'paramedic'],
  'Fishes': ['fish', 'fisheries', 'fishing', 'marine life', 'aquatic species'],
  'Floods and storm protection': ['flood', 'storm protection', 'flood control', 'hurricane protection'],
  'Food assistance and relief': ['food stamps', 'snap', 'food assistance', 'food aid', 'nutrition assistance'],
  'Food industry and services': ['food industry', 'food service', 'restaurant', 'food processing'],
  'Food supply, safety, and labeling': ['food safety', 'food labeling', 'food supply', 'food inspection'],
  'Foreign aid and international relief': ['foreign aid', 'international aid', 'humanitarian aid', 'development assistance'],
  'Foreign and international banking': ['international banking', 'foreign bank', 'global finance', 'international finance'],
  'Foreign and international corporations': ['multinational corporation', 'foreign corporation', 'international business'],
  'Foreign labor': ['foreign worker', 'guest worker', 'migrant worker', 'temporary worker'],
  'Foreign language and bilingual programs': ['foreign language', 'bilingual education', 'language learning', 'esl'],
  'Foreign loans and debt': ['foreign debt', 'international loan', 'sovereign debt', 'external debt'],
  'Foreign property': ['foreign property', 'overseas property', 'international real estate'],
  'Forests, forestry, trees': ['forest', 'forestry', 'trees', 'timber', 'forest management'],
  'Fraud offenses and financial crimes': ['fraud', 'financial crime', 'white collar crime', 'embezzlement'],
  'Free trade and trade barriers': ['free trade', 'trade barriers', 'trade restrictions', 'protectionism'],
  'Freedom of information': ['freedom of information', 'foia', 'government transparency', 'public records'],
  'Fruit and vegetables': ['fruit', 'vegetables', 'produce', 'fresh food', 'agriculture'],
  'Gambling': ['gambling', 'casino', 'lottery', 'betting', 'gaming'],
  'Games and hobbies': ['games', 'hobbies', 'recreation', 'leisure activities'],
  'General taxation matters': ['tax', 'taxation', 'tax policy', 'tax law'],
  'Genetics': ['genetics', 'genetic research', 'dna', 'genomics', 'heredity'],
  'Geography and mapping': ['geography', 'mapping', 'cartography', 'geographic information', 'gis'],
  'Government buildings, facilities, and property': ['government building', 'federal property', 'government facility', 'public building'],
  'Government corporations and government-sponsored enterprises': ['government corporation', 'gse', 'fannie mae', 'freddie mac'],
  'Government employee pay, benefits, personnel management': ['federal employees', 'civil service', 'government benefits', 'personnel policy'],
  'Government ethics and transparency, public corruption': ['government ethics', 'transparency', 'corruption', 'public integrity'],
  'Government information and archives': ['government information', 'archives', 'records management', 'information systems'],
  'Government lending and loan guarantees': ['government loan', 'loan guarantee', 'federal lending', 'government credit'],
  'Government liability': ['government liability', 'federal liability', 'sovereign immunity', 'tort claims'],
  'Government studies and investigations': ['government study', 'investigation', 'research', 'analysis'],
  'Government trust funds': ['trust fund', 'government fund', 'special fund', 'dedicated fund'],
  'Grain': ['grain', 'wheat', 'corn', 'cereal', 'grain production'],
  'HIV/AIDS': ['hiv', 'aids', 'hiv prevention', 'aids treatment', 'hiv testing'],
  'Hate crimes': ['hate crime', 'bias crime', 'hate violence', 'discrimination violence'],
  'Hazardous wastes and toxic substances': ['hazardous waste', 'toxic substances', 'chemical waste', 'environmental contamination'],
  'Health care costs and insurance': ['health insurance', 'medical costs', 'healthcare affordability', 'premium costs', 'coverage'],
  'Health care coverage and access': ['health coverage', 'healthcare access', 'medical coverage', 'healthcare availability'],
  'Health care quality': ['healthcare quality', 'medical quality', 'patient care', 'quality improvement'],
  'Health facilities and institutions': ['hospital', 'clinic', 'health facility', 'medical center'],
  'Health information and medical records': ['medical records', 'health information', 'patient records', 'medical data'],
  'Health personnel': ['healthcare worker', 'medical personnel', 'health professional', 'medical staff'],
  'Health programs administration and funding': ['health program', 'public health', 'health administration', 'health funding'],
  'Health promotion and preventive care': ['preventive care', 'health promotion', 'wellness', 'disease prevention'],
  'Health technology, devices, supplies': ['medical technology', 'medical device', 'health technology', 'medical equipment'],
  'Hearing, speech, and vision care': ['hearing', 'speech', 'vision', 'audiology', 'ophthalmology'],
  'Hereditary and development disorders': ['genetic disorder', 'hereditary disease', 'birth defect', 'developmental disorder'],
  'Higher education': ['college', 'university', 'graduate school', 'student loans', 'higher ed funding', 'research universities'],
  'Historic sites and heritage areas': ['historic site', 'heritage area', 'historical preservation', 'cultural heritage'],
  'Historical and cultural resources': ['historical resource', 'cultural resource', 'heritage preservation', 'cultural preservation'],
  'Home and outpatient care': ['home care', 'outpatient care', 'home health', 'ambulatory care'],
  'Homeland security': ['homeland security', 'domestic security', 'national security', 'security threat'],
  'Homelessness and emergency shelter': ['homeless', 'homelessness', 'emergency shelter', 'housing assistance'],
  'Horticulture and plants': ['horticulture', 'plants', 'gardening', 'plant science'],
  'Hospital care': ['hospital', 'hospital care', 'inpatient care', 'medical facility'],
  'Lower chamber': ['house of representatives', 'house', 'representative'],
  'Housing and community development funding': ['housing funding', 'community development', 'housing program', 'community funding'],
  'Housing discrimination': ['housing discrimination', 'fair housing', 'rental discrimination', 'housing rights'],
  'Housing finance and home ownership': ['mortgage', 'home loans', 'housing market', 'foreclosure', 'housing finance', 'fannie mae'],
  'Housing for the elderly and disabled': ['senior housing', 'disability housing', 'accessible housing', 'elderly housing'],
  'Housing industry and standards': ['housing industry', 'building standards', 'construction standards', 'housing codes'],
  'Housing supply and affordability': ['affordable housing', 'housing shortage', 'housing affordability', 'low income housing'],
  'Human rights': ['human rights', 'civil rights', 'individual rights', 'basic rights'],
  'Human trafficking': ['human trafficking', 'trafficking', 'modern slavery', 'sex trafficking'],
  'Humanities programs funding': ['humanities', 'arts funding', 'cultural funding', 'neh'],
  'Hunting and fishing': ['hunting', 'fishing', 'wildlife management', 'game management'],
  'Hybrid, electric, and advanced technology vehicles': ['electric vehicle', 'hybrid vehicle', 'ev', 'clean vehicle'],
  'Hydrology and hydrography': ['hydrology', 'water science', 'hydrography', 'water resources'],
  'Immigrant health and welfare': ['immigrant health', 'immigrant welfare', 'immigrant services', 'refugee health'],
  'Immigration status and procedures': ['visa processing', 'immigration court', 'deportation', 'asylum process', 'naturalization'],
  'Immunology and vaccination': ['immunization', 'vaccination', 'vaccine', 'immunology', 'public health'],
  'Income tax credits': ['tax credit', 'income tax credit', 'earned income credit', 'child tax credit'],
  'Income tax deductions': ['tax deduction', 'income tax deduction', 'deductible expense', 'tax write-off'],
  'Income tax deferral': ['tax deferral', 'deferred income', 'retirement account', 'tax postponement'],
  'Income tax exclusion': ['tax exclusion', 'tax exempt income', 'excluded income', 'non-taxable income'],
  'Income tax rates': ['tax rate', 'income tax rate', 'marginal tax rate', 'tax bracket'],
  'Indian claims': ['indian claims', 'tribal claims', 'native american claims', 'land claims'],
  'Indian lands and resources rights': ['indian land', 'tribal land', 'reservation', 'tribal resources'],
  'Indian social and development programs': ['indian program', 'tribal program', 'native american services', 'tribal development'],
  'Industrial facilities': ['industrial facility', 'manufacturing plant', 'factory', 'industrial site'],
  'Industrial policy and productivity': ['industrial policy', 'manufacturing policy', 'productivity', 'industrial development'],
  'Infectious and parasitic diseases': ['infectious disease', 'communicable disease', 'epidemic', 'pandemic'],
  'Inflation and prices': ['inflation', 'price increase', 'cost of living', 'economic inflation'],
  'Infrastructure development': ['infrastructure', 'public works', 'infrastructure investment', 'infrastructure repair'],
  'Insects': ['insects', 'pest control', 'entomology', 'insect management'],
  'Insurance industry and regulation': ['insurance regulation', 'insurance industry', 'insurance policy', 'insurance oversight'],
  'Intellectual property': ['patent', 'trademark', 'copyright', 'intellectual property', 'ip rights'],
  'Intelligence activities, surveillance, classified information': ['intelligence', 'surveillance', 'classified information', 'national security', 'cia'],
  'Interest, dividends, interest rates': ['interest rate', 'dividend', 'investment income', 'financial return'],
  'Intergovernmental relations': ['federalism', 'state federal relations', 'intergovernmental', 'local government'],
  'International exchange and broadcasting': ['international exchange', 'cultural exchange', 'international broadcasting'],
  'International law and treaties': ['international law', 'treaty', 'international agreement', 'international relations'],
  'International monetary system and foreign exchange': ['international monetary', 'foreign exchange', 'currency exchange', 'imf'],
  'International organizations and cooperation': ['international organization', 'un', 'international cooperation', 'multilateral'],
  'International scientific cooperation': ['international science', 'scientific cooperation', 'research collaboration'],
  'Internet, web applications, social media': ['internet regulation', 'social media', 'online privacy', 'net neutrality', 'digital rights'],
  'Judges': ['judge', 'judicial', 'court', 'federal judge', 'judicial appointment'],
  'Judicial procedure and administration': ['judicial procedure', 'court administration', 'judicial system', 'court operations'],
  'Judicial review and appeals': ['judicial review', 'appeal', 'appellate review', 'court review'],
  'Jurisdiction and venue': ['jurisdiction', 'venue', 'legal jurisdiction', 'court jurisdiction'],
  'Juvenile crime and gang violence': ['juvenile crime', 'gang violence', 'youth crime', 'juvenile justice'],
  'Labor market': ['labor market', 'job market', 'employment market', 'workforce'],
  'Labor standards': ['labor standards', 'working conditions', 'workplace standards', 'labor protection'],
  'Labor-management relations': ['labor relations', 'union', 'collective bargaining', 'labor dispute'],
  'Lakes and rivers': ['lake', 'river', 'waterway', 'freshwater', 'inland water'],
  'Land transfers': ['land transfer', 'property transfer', 'real estate transfer', 'land sale'],
  'Land use and conservation': ['land use', 'conservation', 'land management', 'zoning'],
  'Landlord and tenant': ['landlord', 'tenant', 'rental property', 'lease agreement'],
  'Language arts': ['language arts', 'english', 'reading', 'writing', 'literature'],
  'Law enforcement administration and funding': ['police funding', 'law enforcement grants', 'police training', 'law enforcement equipment'],
  'Law enforcement officers': ['police officer', 'law enforcement', 'sheriff', 'deputy', 'patrol officer'],
  'Lawyers and legal services': ['lawyer', 'attorney', 'legal services', 'legal profession', 'bar association'],
  'Lease and rental services': ['lease', 'rental', 'rental service', 'equipment lease'],
  'Legal fees and court costs': ['legal fees', 'court costs', 'attorney fees', 'litigation costs'],
  'Legislative rules and procedure': ['legislative procedure', 'congressional rules', 'parliamentary procedure'],
  'Libraries and archives': ['library', 'archive', 'public library', 'library services'],
  'Licensing and registrations': ['license', 'registration', 'permit', 'professional license'],
  'Life, casualty, property insurance': ['life insurance', 'casualty insurance', 'property insurance', 'insurance coverage'],
  'Lighting, heating, cooling': ['lighting', 'heating', 'cooling', 'hvac', 'energy efficiency'],
  'Livestock': ['livestock', 'cattle', 'animals', 'animal husbandry', 'ranching'],
  'Long-term, rehabilitative, and terminal care': ['long-term care', 'rehabilitation', 'terminal care', 'nursing care'],
  'Low- and moderate-income housing': ['low income housing', 'affordable housing', 'public housing', 'housing assistance'],
  'Mammals': ['mammals', 'mammalian', 'wildlife', 'marine mammals'],
  'Manufacturing': ['manufacturing', 'production', 'factory', 'industrial production'],
  'Marine and coastal resources, fisheries': ['marine resources', 'coastal resources', 'fisheries', 'ocean resources'],
  'Marine and inland water transportation': ['shipping', 'maritime transport', 'water transport', 'inland waterway'],
  'Marine pollution': ['marine pollution', 'ocean pollution', 'water pollution', 'maritime environment'],
  'Marketing and advertising': ['marketing', 'advertising', 'promotion', 'commercial advertising'],
  'Marriage and family status': ['marriage', 'family status', 'marital status', 'domestic partnership'],
  'Materials': ['materials', 'raw materials', 'construction materials', 'industrial materials'],
  'Meat': ['meat', 'beef', 'pork', 'meat processing', 'meat industry'],
  'Medicaid': ['medicaid', 'medical assistance', 'healthcare coverage', 'public health insurance'],
  'Medical education': ['medical school', 'medical education', 'medical training', 'healthcare education'],
  'Medical ethics': ['medical ethics', 'bioethics', 'healthcare ethics', 'patient rights'],
  'Medical research': ['medical research', 'biomedical research', 'clinical research', 'health research'],
  'Medical tests and diagnostic methods': ['medical test', 'diagnostic', 'medical screening', 'laboratory test'],
  'Medicare': ['medicare benefits', 'medicare funding', 'medicare reform', 'senior healthcare', 'medicare advantage'],
  'Members': ['congressman', 'senator', 'representative', 'member of congress'],
  'Mental health': ['mental illness', 'psychological services', 'behavioral health', 'mental health treatment', 'suicide prevention'],
  'Metals': ['metals', 'steel', 'aluminum', 'mining', 'metallurgy'],
  'Migrant, seasonal, agricultural labor': ['migrant worker', 'seasonal worker', 'agricultural labor', 'farm worker'],
  'Military assistance, sales, and agreements': ['military assistance', 'arms sales', 'military aid', 'defense cooperation'],
  'Military civil functions': ['military civil', 'army corps', 'military engineering', 'civil works'],
  'Military command and structure': ['military command', 'military structure', 'chain of command', 'military organization'],
  'Military education and training': ['military education', 'military training', 'officer training', 'military academy'],
  'Military facilities and property': ['military base', 'military facility', 'defense facility', 'military installation'],
  'Military history': ['military history', 'war history', 'military heritage', 'veterans history'],
  'Military law': ['military law', 'court martial', 'military justice', 'ucmj'],
  'Military medicine': ['military medicine', 'combat medicine', 'military healthcare', 'battlefield medicine'],
  'Military operations and strategy': ['military operations', 'military strategy', 'defense strategy', 'combat operations'],
  'Military personnel and dependents': ['military families', 'veteran benefits', 'military housing', 'military healthcare', 'deployment'],
  'Military procurement, research, weapons development': ['military procurement', 'weapons development', 'defense research', 'military technology'],
  'Military readiness': ['military readiness', 'combat readiness', 'defense preparedness', 'force readiness'],
  'Militias and paramilitary groups': ['militia', 'paramilitary', 'armed group', 'private military'],
  'Mining': ['mining', 'mineral extraction', 'coal mining', 'mining industry'],
  'Minority and disadvantaged businesses': ['minority business', 'disadvantaged business', 'small business', 'mbe'],
  'Minority education': ['minority education', 'educational equity', 'minority students', 'diverse education'],
  'Minority employment': ['minority employment', 'employment diversity', 'equal opportunity', 'affirmative action'],
  'Minority health': ['minority health', 'health disparities', 'health equity', 'diverse health'],
  'Missing persons': ['missing person', 'missing children', 'amber alert', 'search and rescue'],
  'Monetary policy': ['monetary policy', 'federal reserve', 'interest rates', 'money supply'],
  'Monuments and memorials': ['monument', 'memorial', 'historic site', 'commemoration'],
  'Motor carriers': ['trucking', 'motor carrier', 'commercial vehicle', 'freight transport'],
  'Motor fuels': ['gasoline', 'diesel', 'motor fuel', 'fuel standards'],
  'Motor vehicles': ['automobile', 'car', 'truck', 'vehicle safety', 'automotive'],
  'Multilateral development programs': ['multilateral development', 'world bank', 'development bank', 'international development'],
  'Musculoskeletal and skin diseases': ['musculoskeletal', 'bone disease', 'skin disease', 'orthopedic'],
  'Museums, exhibitions, cultural centers': ['museum', 'exhibition', 'cultural center', 'art gallery'],
  'Music': ['music', 'musical', 'sound recording', 'music industry'],
  'National Guard and reserves': ['national guard', 'military reserves', 'reserve forces', 'guard duty'],
  'National and community service': ['national service', 'community service', 'volunteer service', 'americorps'],
  'National symbols': ['national symbol', 'flag', 'national anthem', 'patriotic symbol'],
  'Natural disasters': ['natural disaster', 'hurricane', 'earthquake', 'tornado', 'flood'],
  'Navigation, waterways, harbors': ['navigation', 'waterway', 'harbor', 'port', 'shipping channel'],
  'Neurological disorders': ['neurological disorder', 'brain disease', 'nervous system', 'neurology'],
  'News media and reporting': ['news media', 'journalism', 'press', 'media reporting'],
  'Normal trade relations, most-favored-nation treatment': ['normal trade relations', 'most favored nation', 'trade status', 'mfn'],
  'Nuclear power': ['nuclear power', 'nuclear energy', 'nuclear reactor', 'atomic energy'],
  'Nuclear weapons': ['nuclear weapons', 'nuclear arms', 'atomic weapons', 'nuclear warhead'],
  'Nursing': ['nursing', 'nurse', 'nursing care', 'registered nurse'],
  'Nutrition and diet': ['nutrition', 'diet', 'food nutrition', 'dietary guidelines'],
  'Oil and gas': ['oil', 'gas', 'petroleum', 'natural gas', 'energy production'],
  'Olympic games': ['olympics', 'olympic games', 'international sports', 'athletic competition'],
  'Organ and tissue donation and transplantation': ['organ donation', 'transplant', 'tissue donation', 'organ transplant'],
  'Organized crime': ['organized crime', 'mafia', 'criminal organization', 'racketeering'],
  'Outdoor recreation': ['outdoor recreation', 'camping', 'hiking', 'outdoor activities'],
  'Palestinians': ['palestinian', 'palestine', 'middle east', 'palestinian affairs'],
  'Parks, recreation areas, trails': ['park', 'recreation area', 'trail', 'public recreation'],
  'Pedestrians and bicycling': ['pedestrian', 'bicycling', 'walking', 'bike safety'],
  'Performance measurement': ['performance measurement', 'government performance', 'accountability', 'metrics'],
  'Performing arts': ['performing arts', 'theater', 'dance', 'music performance'],
  'Personnel records': ['personnel records', 'employee records', 'hr records', 'employment history'],
  'Pest management': ['pest control', 'pesticide', 'pest management', 'insect control'],
  'Photography and imaging': ['photography', 'imaging', 'digital imaging', 'photographic'],
  'Physical fitness and lifestyle': ['physical fitness', 'exercise', 'health promotion', 'wellness'],
  'Pipelines': ['pipeline', 'oil pipeline', 'gas pipeline', 'energy transport'],
  'Policy sciences': ['policy science', 'public policy', 'policy analysis', 'policy research'],
  'Political advertising': ['political advertising', 'campaign advertising', 'political commercials'],
  'Political movements and philosophies': ['political movement', 'political philosophy', 'political ideology'],
  'Political parties and affiliation': ['political party', 'republican', 'democrat', 'political affiliation'],
  'Pollution liability': ['pollution liability', 'environmental liability', 'cleanup liability'],
  'Pornography': ['pornography', 'obscenity', 'adult content', 'sexual content'],
  'Postal service': ['postal service', 'mail', 'usps', 'mail delivery'],
  'Poverty and welfare assistance': ['poverty', 'welfare', 'public assistance', 'social services'],
  'Preschool education': ['preschool', 'early childhood education', 'kindergarten', 'pre-k'],
  'Prescription drugs': ['prescription drugs', 'pharmaceuticals', 'medication', 'drug therapy'],
  'Presidential administrations': ['presidential administration', 'executive branch', 'white house'],
  'Presidents and presidential powers, Vice Presidents': ['president', 'presidential power', 'vice president', 'executive power'],
  'Private Legislation': ['private legislation', 'private bill', 'individual relief', 'special legislation'],
  'Product development and innovation': ['product development', 'innovation', 'research and development', 'new products'],
  'Product safety and quality': ['product safety', 'quality control', 'consumer safety', 'product standards'],
  'Professional sports': ['professional sports', 'nfl', 'nba', 'mlb', 'sports league'],
  'Property rights': ['property rights', 'real property', 'property law', 'ownership rights'],
  'Protection of officials': ['official protection', 'security detail', 'secret service', 'executive protection'],
  'Protest and dissent': ['protest', 'demonstration', 'civil disobedience', 'political dissent'],
  'Public contracts and procurement': ['government contract', 'procurement', 'public contracting', 'federal contracting'],
  'Public housing': ['public housing', 'government housing', 'housing authority', 'subsidized housing'],
  'Public participation and lobbying': ['public participation', 'lobbying', 'citizen engagement', 'public input'],
  'Public transit': ['public transit', 'mass transit', 'public transportation', 'subway'],
  'Public utilities and utility rates': ['public utility', 'utility rates', 'electric utility', 'water utility'],
  'Public-private cooperation': ['public private partnership', 'ppp', 'government cooperation', 'private sector'],
  'Racial and ethnic relations': ['race relations', 'ethnic relations', 'racial equality', 'diversity'],
  'Radiation': ['radiation', 'radioactive', 'nuclear radiation', 'radiation safety'],
  'Radio spectrum allocation': ['radio spectrum', 'spectrum allocation', 'wireless spectrum', 'fcc'],
  'Radioactive wastes and releases': ['radioactive waste', 'nuclear waste', 'radioactive material', 'nuclear cleanup'],
  'Railroads': ['railroad', 'railway', 'train', 'rail transport'],
  'Real estate business': ['real estate', 'property business', 'real estate industry', 'property development'],
  'Reconstruction and stabilization': ['reconstruction', 'post-conflict', 'stabilization', 'nation building'],
  'Refugees, asylum, displaced persons': ['refugee', 'asylum', 'displaced person', 'asylum seeker'],
  'Regional and metropolitan planning': ['regional planning', 'metropolitan planning', 'urban planning', 'city planning'],
  'Religion': ['religion', 'religious', 'faith', 'church', 'religious freedom'],
  'Reptiles': ['reptiles', 'reptilian', 'snake', 'turtle', 'lizard'],
  'Research administration and funding': ['research funding', 'research administration', 'research grant', 'scientific funding'],
  'Research and development': ['research and development', 'r&d', 'scientific research', 'innovation'],
  'Research ethics': ['research ethics', 'scientific ethics', 'research integrity', 'ethical research'],
  'Residential rehabilitation and home repair': ['home repair', 'residential rehabilitation', 'housing rehabilitation', 'home improvement'],
  'Retail and wholesale trades': ['retail', 'wholesale', 'trade', 'commerce', 'business'],
  'Right of privacy': ['privacy', 'privacy rights', 'personal privacy', 'data privacy'],
  'Roads and highways': ['road', 'highway', 'interstate', 'transportation infrastructure'],
  'Rule of law and government transparency': ['rule of law', 'transparency', 'government accountability', 'open government'],
  'Rural conditions and development': ['rural', 'rural development', 'rural community', 'rural economy'],
  'Sales and excise taxes': ['sales tax', 'excise tax', 'consumption tax', 'state tax'],
  'Sanctions': ['sanctions', 'economic sanctions', 'trade sanctions', 'international sanctions'],
  'School administration': ['school administration', 'school management', 'educational administration'],
  'School athletics': ['school sports', 'high school athletics', 'student athletics', 'school teams'],
  'Science and engineering education': ['stem education', 'science education', 'engineering education', 'technical education'],
  'Scientific communication': ['scientific communication', 'research publication', 'scientific journal'],
  'Seafood': ['seafood', 'fish', 'shellfish', 'marine food'],
  'Seashores and lakeshores': ['seashore', 'lakeshore', 'coastal area', 'shoreline'],
  'Securities': ['securities', 'stocks', 'bonds', 'investment securities'],
  'Self-employed': ['self-employed', 'independent contractor', 'freelancer', 'entrepreneur'],
  'Upper chamber': ['senate', 'senator', 'upper house', 'senatorial'],
  'Separation, divorce, custody, support': ['divorce', 'separation', 'child custody', 'child support'],
  'Service animals': ['service animal', 'guide dog', 'assistance animal', 'therapy animal'],
  'Service industries': ['service industry', 'service sector', 'business services', 'professional services'],
  'Sex and reproductive health': ['reproductive health', 'sexual health', 'family planning', 'reproductive rights'],
  'Sex offenses': ['sex offense', 'sexual assault', 'rape', 'sexual crime'],
  'Sex, gender, sexual orientation discrimination': ['gender discrimination', 'sexual orientation discrimination', 'lgbt discrimination', 'gender equality'],
  'Sexually transmitted diseases': ['std', 'sexually transmitted disease', 'venereal disease', 'sexual health'],
  'Small business': ['small business loans', 'sba', 'entrepreneur support', 'minority business', 'small business development'],
  'Smuggling and trafficking': ['smuggling', 'trafficking', 'illegal transport', 'contraband'],
  'Social security and elderly assistance': ['social security', 'elderly assistance', 'senior benefits', 'retirement benefits'],
  'Social work, volunteer service, charitable organizations': ['social work', 'volunteer service', 'charity', 'nonprofit organization'],
  'Soil pollution': ['soil pollution', 'soil contamination', 'ground pollution', 'land contamination'],
  'Solid waste and recycling': ['solid waste', 'recycling', 'waste management', 'garbage disposal'],
  'Sound recording': ['sound recording', 'music recording', 'audio recording', 'recording industry'],
  'Sovereignty, recognition, national governance and status': ['sovereignty', 'national recognition', 'statehood', 'national status'],
  'Space flight and exploration': ['space exploration', 'space flight', 'astronaut', 'space mission'],
  'Spacecraft and satellites': ['spacecraft', 'satellite', 'space vehicle', 'space technology'],
  'Special education': ['special education', 'special needs', 'disability education', 'individualized education'],
  'Specialized courts': ['specialized court', 'drug court', 'family court', 'veterans court'],
  'Sports and recreation facilities': ['sports facility', 'recreation facility', 'gymnasium', 'sports complex'],
  'State and local courts': ['state court', 'local court', 'municipal court', 'county court'],
  'State and local finance': ['state finance', 'local finance', 'municipal finance', 'state budget'],
  'State and local government operations': ['state government', 'local government', 'municipal government', 'state operations'],
  'State and local taxation': ['state tax', 'local tax', 'property tax', 'municipal tax'],
  'Strategic materials and reserves': ['strategic materials', 'strategic reserves', 'national stockpile', 'critical materials'],
  'Student aid and college costs': ['student aid', 'financial aid', 'college costs', 'tuition assistance'],
  'Student records': ['student records', 'academic records', 'educational records', 'transcript'],
  'Subversive activities': ['subversive activity', 'domestic terrorism', 'sedition', 'national security threat'],
  'Supreme Court': ['supreme court', 'scotus', 'high court', 'constitutional court'],
  'Surgery and anesthesia': ['surgery', 'surgical', 'anesthesia', 'medical procedure'],
  'Tariffs': ['tariff', 'import duty', 'customs duty', 'trade tariff'],
  'Tax administration and collection, taxpayers': ['tax administration', 'tax collection', 'irs', 'taxpayer'],
  'Tax reform and tax simplification': ['tax reform', 'tax simplification', 'tax code reform', 'tax overhaul'],
  'Tax treatment of families': ['family tax', 'child tax credit', 'marriage tax', 'dependent exemption'],
  'Tax-exempt organizations': ['tax exempt', 'nonprofit', '501c3', 'charitable organization'],
  'Taxation of foreign income': ['foreign income tax', 'international tax', 'offshore income', 'foreign tax'],
  'Teaching, teachers, curricula': ['teaching', 'teacher', 'curriculum', 'education', 'instruction'],
  'Technology assessment': ['technology assessment', 'technology evaluation', 'tech impact', 'technology policy'],
  'Technology transfer and commercialization': ['technology transfer', 'tech commercialization', 'innovation transfer', 'tech licensing'],
  'Telecommunication rates and fees': ['telecom rates', 'phone rates', 'communication fees', 'telecom pricing'],
  'Telephone and wireless communication': ['telephone', 'wireless', 'cellular', 'mobile phone', 'telecommunications'],
  'Television and film': ['television', 'tv', 'film', 'movie', 'entertainment industry'],
  'Temporary and part-time employment': ['temporary employment', 'part-time work', 'contract work', 'gig economy'],
  'Terrorism': ['terrorism', 'terrorist', 'counterterrorism', 'national security', 'security threat'],
  'Time and calendar': ['time', 'calendar', 'daylight saving', 'time zone'],
  'Trade adjustment assistance': ['trade adjustment', 'worker retraining', 'displaced worker', 'trade assistance'],
  'Trade agreements and negotiations': ['trade agreement', 'trade negotiation', 'trade deal', 'commercial agreement'],
  'Trade restrictions': ['trade restriction', 'import restriction', 'export control', 'trade barrier'],
  'Trade secrets and economic espionage': ['trade secret', 'economic espionage', 'industrial espionage', 'intellectual property theft'],
  'Transfer and inheritance taxes': ['inheritance tax', 'estate tax', 'gift tax', 'transfer tax'],
  'Transportation costs': ['transportation cost', 'shipping cost', 'freight cost', 'transport expense'],
  'Transportation employees': ['transportation worker', 'transit employee', 'transportation labor', 'transport staff'],
  'Transportation programs funding': ['transportation funding', 'highway funding', 'transit funding', 'infrastructure funding'],
  'Transportation safety and security': ['traffic safety', 'vehicle safety', 'transportation security', 'aviation security', 'railroad safety'],
  'Travel and tourism': ['travel', 'tourism', 'tourist', 'hospitality', 'travel industry'],
  'U.S. Capitol': ['capitol', 'capitol building', 'congress building', 'legislative building'],
  'U.S. and foreign investments': ['foreign investment', 'international investment', 'cross-border investment', 'fdi'],
  'U.S. history': ['american history', 'us history', 'historical', 'american heritage'],
  'U.S. territories and protectorates': ['territory', 'protectorate', 'puerto rico', 'guam', 'virgin islands'],
  'Unemployment': ['unemployment', 'jobless', 'unemployment benefits', 'unemployment insurance'],
  'Urban and suburban affairs and development': ['urban development', 'suburban development', 'city development', 'metropolitan'],
  'User charges and fees': ['user fee', 'service charge', 'government fee', 'public fee'],
  'Veterans\' education, employment, rehabilitation': ['veteran education', 'veteran employment', 'veteran rehabilitation', 'gi bill'],
  'Veterans\' loans, housing, homeless programs': ['veteran housing', 'va loan', 'veteran homeless', 'veteran assistance'],
  'Veterans\' medical care': ['va hospitals', 'veteran healthcare', 'military medicine', 'veteran disability', 'ptsd treatment'],
  'Veterans\' organizations and recognition': ['veteran organization', 'veteran recognition', 'veteran service', 'veteran honor'],
  'Veterans\' pensions and compensation': ['veteran pension', 'veteran compensation', 'disability compensation', 'veteran benefits'],
  'Veterinary medicine and animal diseases': ['veterinary', 'animal disease', 'animal health', 'veterinary medicine'],
  'Violent crime': ['violent crime', 'violent offense', 'assault', 'murder', 'robbery'],
  'Visas and passports': ['visa', 'passport', 'travel document', 'immigration document'],
  'Vocational and technical education': ['vocational education', 'technical education', 'trade school', 'career training'],
  'Voting rights': ['voting rights', 'suffrage', 'electoral rights', 'ballot access'],
  'Wages and earnings': ['wage', 'salary', 'earnings', 'income', 'compensation'],
  'War and emergency powers': ['war powers', 'emergency powers', 'martial law', 'wartime authority'],
  'War crimes, genocide, crimes against humanity': ['war crimes', 'genocide', 'crimes against humanity', 'international crime'],
  'Water quality': ['water pollution', 'drinking water', 'water standards', 'clean water act', 'water contamination'],
  'Water resources funding': ['water funding', 'water infrastructure', 'water project funding', 'water investment'],
  'Water storage': ['water storage', 'reservoir', 'water supply', 'water conservation'],
  'Water use and supply': ['water supply', 'water use', 'water rights', 'water allocation'],
  'Watersheds': ['watershed', 'river basin', 'drainage basin', 'water catchment'],
  'Wetlands': ['wetland', 'marsh', 'swamp', 'bog', 'wetland conservation'],
  'Wilderness and natural areas, wildlife refuges, wild rivers, habitats': ['wilderness', 'wildlife refuge', 'natural area', 'habitat protection'],
  'Wildlife conservation and habitat protection': ['wildlife conservation', 'habitat protection', 'species protection', 'conservation biology'],
  'Women in business': ['women in business', 'female entrepreneur', 'women owned business', 'gender business'],
  'Women\'s education': ['women education', 'female education', 'girls education', 'gender education'],
  'Women\'s employment': ['women employment', 'female employment', 'gender employment', 'workplace gender'],
  'Women\'s health': ['women health', 'maternal health', 'reproductive health', 'female health'],
  'Women\'s rights': ['women rights', 'gender rights', 'female rights', 'gender equality'],
  'Worker safety and health': ['workplace safety', 'occupational safety', 'worker health', 'osha'],
  'World health': ['global health', 'international health', 'world health organization', 'public health'],
  'World history': ['world history', 'international history', 'global history', 'foreign history'],
  'Youth employment and child labor': ['youth employment', 'child labor', 'teenage employment', 'young worker']
};

export interface ClassificationResult {
  broadTopics: string[];
  narrowTopics: string[];
  confidence: number;
  reasoning: string;
}
